### PR TITLE
Hover and workspace fixes post merge

### PR DESCRIPTION
**Pull request by arichiardi**
Hi Laurent,
I had to clean up ```StaticStrings``` and do a change in the font name (they suggest to use ```JFaceResources.DIALOG_FONT``` now).

Moreover, I fixed the workspace, if you have not already, so that now Eclipse compiles again.

:v:

### CODE REVIEW

**Comment by arichiardi** [comment]
If you wait a bit, I have another fix coming...Basically I noticed that all the ```<pre>``` tags were cut in the hovers. I then investigated and noticed that the ```BrowserInformationControl``` was using ```HTML2TextReader``` to convert ```html``` to text and then calculate the width.
This of course does not consider that ```<pre>``` tags are ```monospace```, therefore bigger.

Now, two options:
1) Change the ```<pre>``` tag in something different, losing ```monospace``` (that I like).
2) Find a way to consider the bigger font size of ```<pre>```.

I am going to check if there is a way to obtain number 2) .

**Comment by laurentpetit** [comment]
I can wait :-)

**Comment by arichiardi** [comment]
Working on this now.

**Comment by arichiardi** [comment]
Rebased and added my hackity-hack for fixing the hover control. It has been interesting, but I solved, ```BrowserInformationControl``` would really need some rework.
I have basically added monospace font utilities (using an Eclipse's bug attachment) and used it in order to compute the right size for my ```<pre>``` tags, overriding standard behaviors in a (hopefully) graceful way (using Math.max).
Have a look if you'd like and tell me what you think :smile:

**Comment by laurentpetit** [comment]
Ok sorry for the delay on this, the problem with AOT compilation drained all my focus these past days.

**Comment by arichiardi** [comment]
No problem don't worry :)

**Comment by laurentpetit** [comment]
I see that you continued working on the same branch? Maybe you should start another one. I cannot automatically merge right now

**Comment by laurentpetit** [comment]
and I think if I would I would embed new work pushed 9 hours ago?

**Comment by arichiardi** [comment]
I am rebasing this now...it contains just refactoring and fixes that in general are needed for adding hovers (as I am working on another branch on the Macro hover). Of course if you think so I can embed them in that branch, but I have tried at every commit and they are not breaking anything...

**Comment by arichiardi** [comment]
This should be good now.

**Comment by laurentpetit** [comment]
Ok I will merge then

**Pull request merged**
