### PR TITLE
cider-nrepl pprint

### PR DESCRIPTION
**Pull request by laurentpetit**

### CODE REVIEW

**Comment by laurentpetit** [comment]
Hi @arichiardi this is a small PR adding `pprint` support to the REPL (as long as `cider-nrepl` is found, because currently only this back-end offers `pprint` middleware).

Can you find some time to review/test it?

**Comment by arichiardi** [comment]
When ```mvn clean install``` do you have the same error:

    [ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:0.21.0:package-plugin (default-package-plugin) on project ccw.core: /home/kapitan/git/ccw/ccw.core/build.properties: bin.includes value(s) [lib/debugger-jar/] do not match any files. -> [Help 1]
    org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:0.21.0:package-plugin (default-package-plugin) on project ccw.core: /home/kapitan/git/ccw/ccw.core/build.properties: bin.includes value(s) [lib/debugger-jar/] do not match any files.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)

**Comment by arichiardi** [comment]
And at runtime I have:

    java.lang.ClassNotFoundException: ccw.leiningen.LeiningenBuilder cannot be found by ccw.core_0.31.2.qualifier
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

**Comment by laurentpetit** [comment]
Oh, this is probably a moving dependency of cider-nrepl. I hope version
0.9.0 will get out soon :-)

2015-04-28 18:59 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> And at runtime I have:
>
> java.lang.ClassNotFoundException: ccw.leiningen.LeiningenBuilder cannot be found by ccw.core_0.31.2.qualifier
> at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
> at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
> at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
> at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/753#issuecomment-97136930>.
>



-- 
Laurent Petit

**Comment by laurentpetit** [comment]
I will commit the fix on master, and then rebase cider-nrepl on top of it

2015-04-28 19:29 GMT+02:00 Laurent PETIT <laurent.petit@gmail.com>:

> Oh, this is probably a moving dependency of cider-nrepl. I hope version
> 0.9.0 will get out soon :-)
>
> 2015-04-28 18:59 GMT+02:00 Andrea Richiardi <notifications@github.com>:
>
>> And at runtime I have:
>>
>> java.lang.ClassNotFoundException: ccw.leiningen.LeiningenBuilder cannot be found by ccw.core_0.31.2.qualifier
>> at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
>> at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
>> at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
>> at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
>> at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/laurentpetit/ccw/pull/753#issuecomment-97136930>.
>>
>
>
>
> --
> Laurent Petit
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
:+1:

**Comment by laurentpetit** [comment]
Done I force pushed a new version of the `cider-pprint` PR branch

**Comment by arichiardi** [comment]
OK  i am going to test!

**Comment by arichiardi** [comment]
Should it work "at runtime" ? meaning that I have a REPL and I switch the feature on and off...should it pprint/not pprint accordingly?

**Comment by arichiardi** [comment]
I would put PPrint all downcase, it feels weird to me like this (maybe I am just crazy :D)...

**Comment by laurentpetit** [comment]
Yes, it should work at runtime. I think I made it so. Isn't that the case?

**Comment by laurentpetit** [comment]
Where would you out PPrint all down case ? It is the case in the clojure code, and in the Java code I must follow the CamelCase convention when there are multiple words. What is your suggestion for the several different variable/method names exactly?

**Comment by arichiardi** [comment]
No sorry, it was just a suggestion for the preference page..

**Comment by arichiardi** [comment]
There is a weird thing, when the ```PPrint``` feature is on, the Repl output is not colored anymore.
selection_003

**Comment by arichiardi** [comment]
When I switch off the feature from the preference page, the coloring is back to normal, I have never been able to see my ```m``` pprinted though.

**Comment by laurentpetit** [comment]
good catch, I changed it to lower case ; it was weird looking indeed

2015-04-29 10:30 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> No sorry, it was just a suggestion for the preference page..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/753#issuecomment-97351679>.
>



-- 
Laurent Petit

**Comment by laurentpetit** [comment]
## black instead of green
What cider-nrepl does is that when pprint is enabled, it pprints the value
to its *out* in addition to returning the value.
Thus things where displayed twice: once in black as everything that is
Printed by the nREPL and pprinted, and once in green, not pprinted.
I managed to not show the green value that was redundent.

Note: I have ideas for syntax highligthing results, so this may change
again in the future.

## value not pprinted

There is a `:right-margin` option to the `pprint` middleware, which is then
passed to the `pprint` function. Currently it is set to a value of `80`.
This may explain why your value is not displayed.
Maybe we can lower this value to better fit most where the REPL is not as
large as the screen, and also because 80 chars wide data/edn is a lot to
read.
What about trying to cut it down to 40 ?


2015-04-29 10:35 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> When I switch off the feature from the preference page, the coloring is
> back to normal, I have never been able to see my m pprinted though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/753#issuecomment-97352294>.
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
No sorry, an image is not clear. What you see up there are different CTRL-ENTER. The first is with pprint off, the others with pprint on. It consistently shows black when on, green when on. And not just the single evaluation, but all the subsequent ones...

**Comment by laurentpetit** [comment]
Once it is on, black will be used as long as it is not turned on again. This seems coherent to me.
I don't think it's feasible to turn it green again, because it's how cider-nrepl works

**Comment by arichiardi** [comment]
Ok then but what about the pretty printing? it is not shown in that cas, but if I ```(use clojure.pprint)``` it works.

**Comment by laurentpetit** [comment]
This is weird. I am working on adding an option in the preferences to give the user the ability to set a custom value for the `:right-margin`.
And also change its default value from `80` to `40` BTW.
Will push it soon

**Comment by laurentpetit** [comment]
Maybe try to do a `mvn clean verify` on your project to gather the last version of `cider-nrepl` again? Because it is working for me with the default value of 40, with the value of 80, so that's weird.

I will push the new version

**Comment by laurentpetit** [comment]
My bad, my code was not correct and I was always testing with a value of `80` for `:right-margin`. Now that it is corrected, I can see that with a value of `80` I get the same behavior as you get, and with a value of `40` I get a decent pretty-printing.

**Comment by arichiardi** [comment]
Oh great, I was going bananas :)

**Comment by laurentpetit** [comment]
Waiting for a more explicit go :-)

**Comment by arichiardi** [comment]
It works, good to go!

**Pull request merged**
