### PR TITLE
AOT compiled CCW

### PR DESCRIPTION
**Pull request by laurentpetit**

### CODE REVIEW

**Comment by laurentpetit** [comment]
For this to work, I had to
 -fix CCW
- fork `clojure-maven-plugin` to add a feature for deleting some unwanted aot classes
- release a new version of `ccw/clojure-ccw`

**Comment by laurentpetit** [comment]
@arichiardi this PR has been really hard to produce, but I finally got it out!
Don't hesitate to comment the code, ask questions, test (a packaged version, the plugin), etc.

**Comment by arichiardi** [comment]
Yes, I was thinking exactly the same :smile:

**Comment by arichiardi** [comment]
I have an error on ```mvn clean compile```:

<code>
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project ccw:ccw.core:0.31.2-SNAPSHOT (/home/kapitan/git/ccw/ccw.core/pom.xml) has 2 errors
[ERROR]     Unresolveable build extension: Plugin ccw:clojure-maven-plugin:1.3.24-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact ccw:clojure-maven-plugin:jar:1.3.24-SNAPSHOT in tycho (https://oss.sonatype.org/content/groups/public/) -> [Help 2]
[ERROR]     Unknown packaging: eclipse-plugin @ line 17, column 14
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
</code>

**Comment by laurentpetit** [comment]
Try to compile with the -U option passed to maven. If it still doesn't
work, then maybe it's because the deploys to clojure failed. In this last
resort case, you can clone my fork of clojure-maven-plugin and 'mvn clean
install' it locally

Le samedi 16 mai 2015, Andrea Richiardi <notifications@github.com> a écrit :

> I have an error on mvn clean compile:
>
>
> [ERROR] The build could not read 1 project -> [Help 1]
> [ERROR]
>
> [ERROR] The project ccw:ccw.core:0.31.2-SNAPSHOT
> (/home/kapitan/git/ccw/ccw.core/pom.xml) has 2 errors
> [ERROR] Unresolveable build extension: Plugin
> ccw:clojure-maven-plugin:1.3.24-SNAPSHOT or one of its dependencies could
> not be resolved: Could not find artifact
> ccw:clojure-maven-plugin:jar:1.3.24-SNAPSHOT in tycho (
> https://oss.sonatype.org/content/groups/public/) -> [Help 2]
> [ERROR] Unknown packaging: eclipse-plugin @ line 17, column 14
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the
> -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/767#issuecomment-102646714>.
>


-- 
Laurent Petit

**Comment by laurentpetit** [comment]
Understood. I had to add clojars to the pluginRepositories in addition to being in the repositories

**Comment by laurentpetit** [comment]
@arichiardi problem should be gone

**Comment by arichiardi** [comment]
Great will test this branch

**Comment by arichiardi** [comment]
Everything is so fast now! :smile:
An issue on this, maybe not that important...by mistake, I closed ccw before finishing loading all the namespaces, and I got:

    !ENTRY org.eclipse.osgi 2 0 2015-05-17 10:08:59.544
    !MESSAGE State change in progress for bundle "reference:file:/home/kapitan/git/ccw/ccw.core/" by thread "main".
    !STACK 0
    org.osgi.framework.BundleException: State change in progress for bundle "reference:file:/home/kapitan/git/ccw/ccw.core/" by thread "main".
    at org.eclipse.osgi.framework.internal.core.AbstractBundle.beginStateChange(AbstractBundle.java:1088)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.start(AbstractBundle.java:298)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:478)
	at org.eclipse.osgi.internal.loader.BundleLoader.setLazyTrigger(BundleLoader.java:263)
	at org.eclipse.osgi.framework.internal.core.BundleHost.loadClass(BundleHost.java:236)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.loadClass(AbstractBundle.java:1212)
	at ccw.util.osgi.BundleClassLoader.findClass(BundleClassLoader.java:27)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at clojure.lang.RT.classForName(RT.java:2155)
	at clojure.lang.RT.classForNameNonLoading(RT.java:2168)
	at clojure.lang.RT.loadClassForName(RT.java:2174)
	at clojure.lang.RT.load(RT.java:436)
	[...]

**Comment by arichiardi** [comment]
I have run it from within Eclipse, using the Debug configuration and if I don't terminate the process explicitly, with the red button, it never ends, still trying to load namespaces...
I guess this won't happen normally, but it might be good to have a look at cancelling the loading stopping the background thread as soon as possible. I am thinking of this mostly because it can be useful for users that want to stop loading, say, a Leiningen Repl session.

**Comment by laurentpetit** [comment]
Ok so while eclipse is closing and shutting down bundles, there's nothing we can do if we get a BundleException right ?

We could either use the CCWPlugin stop() method to set a flag, that we can then check before logging the exception (and then not log it, maybe just trace it if debug traces are enabled)

Or we could directly check the bundle state without any flag and do the same behavior

Of course, if we could immediately stop the thread that is calling ClojureOsgi that would be even better, but I doubt it will be easy?

**Comment by arichiardi** [comment]
Sorry I was checking that it did not behave the same while stopping a started Leiningen...yes if there is a clean why to hook a cancel...or exit when ```Thread.isInterrupted``` is called maybe is safer...I am just worried that this Exception can show in some other context that now I cannot reproduce..

**Comment by laurentpetit** [comment]
I think that coupled with a check to the bundle state should be enough

**Comment by arichiardi** [comment]
Yep, I noticed a small but important bug in the meantime...I will open an issue ok?

**Comment by laurentpetit** [comment]
Yep. A bug related to the work on AOT?

**Comment by arichiardi** [comment]
No no, this looks good apart from that Exception..that is why I opened another issue..

**Comment by laurentpetit** [comment]
So I'm not sure there is something left to do for now on this branch, @arichiardi ?

**Comment by arichiardi** [comment]
Will we open another issue for that check above? Is not blocking in any case and should not be visible to users anyway...we can merge this...

**Comment by arichiardi** [comment]
I fixed the problem here with bundle activator...I will open a PR ok?

**Pull request merged**
