### PR TITLE
Automated Integration Tests Revival

### PR DESCRIPTION
**Pull request by laurentpetit**
See also #750 for a history of what has been discussed

### CODE REVIEW

**Comment by laurentpetit** [comment]
@arichiardi there we are

**Comment by laurentpetit** [comment]
Hi @arichiardi , is there a compelling reason for having set testFailureIgnore to true in the test pom? I'd prefer test failure to stop the build, as a default.

**Comment by arichiardi** [comment]
Woa! Nice! This is a personal preference I guess, we can of course change it...I think I put it like that because if we don't stop then we have all the reports of the failing cases...and people (you and me at the moment) can independently take and fix them...

**Comment by arichiardi** [comment]
I received some email with failures. It looks like some part I did was not ok, but it compiled on my side...I will re-check...

**Comment by arichiardi** [comment]
Aaaargh! Sorry my auto-build was disabled and I think I forgot a piece... incredible how I was able to test it...probably some old .class contained valid code...

**Comment by laurentpetit** [comment]
Already fixed locally, no worries

2015-05-28 17:03 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> Aaaargh! Sorry my auto-build was disabled and I think I forgot a piece...
> incredible how I was able to test it...probably some old .class contained
> valid code...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/784#issuecomment-106383454>.
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
Ok, me too, but you are first, who pushes :smile: ? Sorry about that.

**Comment by laurentpetit** [comment]
Fix Pushed in the master branch.
If you don't mind, I will merge this PR, even if not reviewed by you already. Because I'd like to advance on integrating it with Jenkins and I need it to be in master.

**Comment by arichiardi** [comment]
ok go ahead, today I am not going to have too much time to test it, but I skimmed the commits and they look ok.

**Comment by laurentpetit** [comment]
@arichiardi please note that if you want to skip integration tests, there's a built-in `skipTests` flag that can be used

**Comment by arichiardi** [comment]
Yes I read it in your commit message, I added it in the first place in order to skip just the ui (```SWTBot```) test but run the others, but I guess it does not add much to the plate.

**Pull request merged**
