### PR TITLE
Repl style listener

### PR DESCRIPTION
**Pull request by laurentpetit**
Rebased and fixed version of #30

### CODE REVIEW

**Comment by arichiardi** [comment]
If you explain some very brief use case I can test !

**Comment by laurentpetit** [comment]
Still too early, there are some problems I'd like to work on, I discovered after having created the PR

**Comment by arichiardi** [comment]
OK :+1

**Comment by laurentpetit** [comment]
OK, now should be good to be tested.
To test this PR:
- install the ansi-repl ccw-plugin: https://github.com/laurentpetit/ccw-plugin-ansi-repl (no doc yet, will work on it tomorrow)
- install the ansi-econsole eclipse plugin from: https://github.com/mihnita/ansi-econsole

Note: the ansi-econsole plugin is not free from gotchas, but is a very good base. So let's start with that, and when facing problems for real, see how we evolve. (problems essentially in the console itself, not the REPL, e.g. in the console it seems that hyperlinks disappear)

**Comment by laurentpetit** [comment]
Hello @arichiardi , did you find some time to test this?

**Comment by arichiardi** [comment]
Hi! I was planning to do it this afternoon.

**Comment by laurentpetit** [comment]
cool!

**Comment by smee** [comment]
https://github.com/laurentpetit/ccw-plugin-ansi-repl/issues/1

**Comment by arichiardi** [comment]
Which version is the plugin compatible with?

With you branch ```repl-style-listener``` I am getting a:
    java.lang.RuntimeException: Incompatible version of Counterclockwise with ansi-repl user plugin, compiling:(/home/kapitan/.ccw/laurentpetit/ccw-plugin-ansi-repl/ansi-repl.clj:32:1)
	at clojure.lang.Compiler.load(Compiler.java:7271)
	at clojure.lang.Compiler.loadFile(Compiler.java:7197)
	at clojure.lang.RT$3.invoke(RT.java:319)
	at ccw.core.user_plugins$load_user_script.invoke(user_plugins.clj:104)
	at ccw.core.user_plugins$start_user_plugin$fn__16516.invoke(user_plugins.clj:118)
	at ccw.core.user_plugins$with_bundle$reify__16501.run(user_plugins.clj:88)
	at ccw.util.osgi.ClojureOSGi.withBundle(ClojureOSGi.java:69)
	at ccw.core.user_plugins$with_bundle.invoke(user_plugins.clj:85)
	at ccw.core.user_plugins$start_user_plugin.invoke(user_plugins.clj:113)
	at ccw.core.user_plugins$start_user_plugins.invoke(user_plugins.clj:141)
	at clojure.lang.Var.invoke(Var.java:375)
	at ccw.util.ClojureUtils.invoke(ClojureUtils.java:28)
	at ccw.util.ClojureInvoker._(ClojureInvoker.java:18)
	at ccw.core.Eclipse4ModelProcessor$1.handleEvent(Eclipse4ModelProcessor.java:48)
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:41)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3717)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3366)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:140)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:611)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1426)
Caused by: java.lang.RuntimeException: Incompatible version of Counterclockwise with ansi-repl user plugin
	at ansi_repl$eval16808.invoke(ansi-repl.clj:33)
	at clojure.lang.Compiler.eval(Compiler.java:6814)
	at clojure.lang.Compiler.load(Compiler.java:7259)
	... 40 more

**Comment by arichiardi** [comment]
Oh I saw the other issue and maybe I am trying with the wrong version...

**Comment by laurentpetit** [comment]
If you checkout branch `repl-style-listener` it should be working.
If you also install user plugin https://github.com/laurentpetit/ccw-plugin-ansi-repl then you should be able to enter e.g. `(println "This is \u001b[1;31mRED\u001b[0m and works.")` and you should see `RED` displayed in red

**Comment by laurentpetit** [comment]
if you have installed the ANSI econsole plugin, of course

**Comment by arichiardi** [comment]
Mmm... I did both...let me check maybe I made some mistake

**Comment by laurentpetit** [comment]
or maybe my last commit in `ccw-plugin-ansi-repl` is too aggressive, Il'l
also check

2015-05-07 15:18 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> Mmm... I did both...let me check maybe I made some mistake
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/755#issuecomment-99860836>.
>



-- 
Laurent Petit

**Comment by laurentpetit** [comment]
My bad, the `ansi-repl` plugin did a compatibility check on the wrong
class! Fixed

2015-05-07 15:20 GMT+02:00 Laurent PETIT <laurent.petit@gmail.com>:

> or maybe my last commit in `ccw-plugin-ansi-repl` is too aggressive, Il'l
> also check
>
> 2015-05-07 15:18 GMT+02:00 Andrea Richiardi <notifications@github.com>:
>
>> Mmm... I did both...let me check maybe I made some mistake
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/laurentpetit/ccw/pull/755#issuecomment-99860836>.
>>
>
>
>
> --
> Laurent Petit
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
Great, testing everything now

**Comment by arichiardi** [comment]
Mmm...still not working with the same exception on my side...

**Comment by laurentpetit** [comment]
yes, i got the .assignableFrom call backwards. Pushed again, sorry for the
noise

2015-05-07 15:31 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> Mmm...still not working with the same exception on my side...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/755#issuecomment-99866848>.
>



-- 
Laurent Petit

**Comment by laurentpetit** [comment]
and now it doesn't work grmmlml what's wrong with me today?

2015-05-07 15:31 GMT+02:00 Laurent PETIT <laurent.petit@gmail.com>:

> yes, i got the .assignableFrom call backwards. Pushed again, sorry for the
> noise
>
> 2015-05-07 15:31 GMT+02:00 Andrea Richiardi <notifications@github.com>:
>
>> Mmm...still not working with the same exception on my side...
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/laurentpetit/ccw/pull/755#issuecomment-99866848>.
>>
>
>
>
> --
> Laurent Petit
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
Ahahah don't worry, it happened to me a lot of times :)

**Comment by arichiardi** [comment]
selection_004

**Comment by laurentpetit** [comment]
Great !

In fact, I was in the middle of a rebase of the branch and did not have
enough commits :-)

2015-05-07 15:35 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> [image: selection_004]
> <https://cloud.githubusercontent.com/assets/1724788/7516300/b710edc8-f4ce-11e4-94fe-22b683486712.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/755#issuecomment-99867706>.
>



-- 
Laurent Petit

**Comment by laurentpetit** [comment]
Take the time to review the commit(s) before giving me the Go to merge, if
you want/need to.

2015-05-07 15:37 GMT+02:00 Laurent PETIT <laurent.petit@gmail.com>:

> Great !
>
> In fact, I was in the middle of a rebase of the branch and did not have
> enough commits :-)
>
> 2015-05-07 15:35 GMT+02:00 Andrea Richiardi <notifications@github.com>:
>
>> [image: selection_004]
>> <https://cloud.githubusercontent.com/assets/1724788/7516300/b710edc8-f4ce-11e4-94fe-22b683486712.png>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/laurentpetit/ccw/pull/755#issuecomment-99867706>.
>>
>
>
>
> --
> Laurent Petit
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
Just a (newbie) question...

Why is [this](https://github.com/laurentpetit/ccw-plugin-ansi-repl/blob/2b09bdc677bf2ec1d504c92389a67813cd0a9dcd/ansi-repl.clj#L90) modified with ```alter-var-root``` ? What is the difference with a simple ```update-in``` if, as he said on top, there is no need for an atom as we will only access to the plugin from the UI thread?

**Comment by laurentpetit** [comment]
Good question. I put much work on reviewing what has been contributed to CCW proper, and not much on the plugin, which I have just debugged so that it works (it wasn't) and "rebundled" as a repo instead of just a gist.

I don't feel like I'll work more on it right now, but if you want to work on it feel free to improve and submit pull requests, they will be welcome since indeed the code could benefit from some love.

**Comment by arichiardi** [comment]
I think I am going to let it be as it is, I am fixing the problems in my PR so that you can merge that as well. Then color/syntax preview fixes as my next step.

**Comment by laurentpetit** [comment]
ok

**Pull request merged**
