### PR TITLE
Cider nrepl

### PR DESCRIPTION
**Pull request by laurentpetit**
PR tracking the implementation of cider-nrepl integration in #734

### CODE REVIEW

**Comment by laurentpetit** [comment]
I've narrowed down the number of tasks in the corresponding Ticket. It is ready, just waiting to be more battle tested

**Comment by arichiardi** [comment]
Wow great! I am going to test it as well, I guess my super patch will need to be reworked a little...

**Comment by arichiardi** [comment]
Ok, I have tried it and here is an exception:

    Exception in thread "AutoAssist Delay" 
    org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
	at org.eclipse.swt.SWT.error(SWT.java:4397)
	at org.eclipse.swt.SWT.error(SWT.java:4312)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:196)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:150)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4491)
	at org.eclipse.jface.text.contentassist.ContentAssistant$AutoAssistListener.showAssist(ContentAssistant.java:367)
	at org.eclipse.jface.text.contentassist.ContentAssistant$AutoAssistListener.run(ContentAssistant.java:279)
    Caused by: java.lang.NullPointerException
	at ccw.debug.serverrepl$textmate_filter.invoke(serverrepl.clj:165)
	at ccw.debug.serverrepl$textmate_filter.invoke(serverrepl.clj:161)
	at ccw.debug.serverrepl$textmate_distance.invoke(serverrepl.clj:176)
	at ccw.debug.serverrepl$distance_comparator$fn__6117.invoke(serverrepl.clj:213)
	at ccw.debug.serverrepl$distance_comparator$fn__6117.invoke(serverrepl.clj:223)
	at ccw.editors.clojure.clojure_proposal_processor$adapt_args$fn__6702.invoke(clojure_proposal_processor.clj:359)
	at clojure.lang.AFunction.compare(AFunction.java:47)
	at clojure.lang.PersistentTreeMap.doCompare(PersistentTreeMap.java:311)
	at clojure.lang.PersistentTreeMap.entryAt(PersistentTreeMap.java:298)
	at clojure.lang.PersistentTreeMap.containsKey(PersistentTreeMap.java:94)
	at clojure.lang.APersistentSet.contains(APersistentSet.java:34)
	at clojure.lang.PersistentTreeSet.cons(PersistentTreeSet.java:52)
	at clojure.lang.PersistentTreeSet.create(PersistentTreeSet.java:35)
	at clojure.core$sorted_set_by.doInvoke(core.clj:414)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:630)
	at ccw.editors.clojure.clojure_proposal_processor$compute_completion_proposals.invoke(clojure_proposal_processor.clj:389)
	at ccw.editors.clojure.clojure_proposal_processor$make_process$reify__6741.computeCompletionProposals(clojure_proposal_processor.clj:463)
	at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:1839)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:566)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$16(CompletionProposalPopup.java:563)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:498)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:492)
	at org.eclipse.jface.text.contentassist.ContentAssistant$2.run(ContentAssistant.java:378)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3717)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3366)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:140)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:611)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)

**Comment by arichiardi** [comment]
It is funny because I totally revisited this part to in my refactoring as well...I guess my change won't be easy to rebase now...

**Comment by laurentpetit** [comment]
:-( sorry

Le lundi 13 avril 2015, Andrea Richiardi <notifications@github.com> a
écrit :

> It is funny because I totally revisited this part to in my refactoring as
> well...I guess my change won't be easy to rebase now...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/735#issuecomment-92320631>.
>


-- 
Laurent Petit

**Comment by laurentpetit** [comment]
So the exception is saying that the completion is nil, interesting. If you are able to reproduce the case, that would be great, 'coz I thing somewhere the `cider-nrepl` middleware sends something unexpected that should be filtered, or at the integration point between `cider-nrepl` and the auto-completion ...

**Comment by laurentpetit** [comment]
Are you using the tip of the `cider-nrepl` branch? The exception reports line 389 of file `clojure_completion_proposal.clj`, but on my branch it's at the middle of a docstring?

**Comment by laurentpetit** [comment]
I pushed a commit which should prevent the exception to ever happen again

**Comment by arichiardi** [comment]
Ok, that looks solved, now this...load a file in repl, define a var (def s '(3 4 5)), then "s+enter" to evaluate the var in the repl...

    java.lang.ClassCastException: java.lang.String cannot be cast to org.eclipse.jface.text.contentassist.IContextInformation
	at ccw.editors.clojure.clojure_proposal_processor$completion_proposal$reify__6639.getContextInformation(clojure_proposal_processor.clj:142)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.insertProposal(CompletionProposalPopup.java:955)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.insertSelectedProposalWithMask(CompletionProposalPopup.java:891)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.verifyKey(CompletionProposalPopup.java:1323)
	at org.eclipse.jface.text.contentassist.ContentAssistant$InternalListener.verifyKey(ContentAssistant.java:808)
	at org.eclipse.jface.text.TextViewer$VerifyKeyListenersManager.verifyKey(TextViewer.java:491)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:65)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1392)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1416)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1401)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1187)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:5954)
	at org.eclipse.swt.custom.StyledText$7.handleEvent(StyledText.java:5636)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1392)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1416)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1401)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1428)
	at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:829)
	at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3236)
	at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:758)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2096)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:5467)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4569)
	at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:8756)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1243)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2302)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3361)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:140)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:611)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1426)

**Comment by laurentpetit** [comment]
Thank you ! I'll work on this.
In the mean time, I just merged master into `cider-nrepl` (I didn't rebase `cider-nrepl` so I don't mess with the history since you're looking at the PR).

**Comment by laurentpetit** [comment]
I wasn't able to reproduce the `(def s '(3 4 5))` problem. But I'll look at the exception anyway and try to fix it.

**Comment by laurentpetit** [comment]
Ok, thank you Andrea, this exception was a very good catch, there was a big hole in the wall. I think I've fixed it now.

**Comment by arichiardi** [comment]
My pleasure, I am going to confirm it tomorrow ;)

**Comment by laurentpetit** [comment]
Hi @arichiardi I have pushed a few more commits to follow `cider-nrepl` development, and also to use `[ccw/clojure-ccw "1.7.0-03"]` which is rebased on top of `[org.clojure/clojure "1.7.0-beta01"]`

**Comment by arichiardi** [comment]
Haven't they merge you patch for OSGi yet?

**Comment by laurentpetit** [comment]
No :-(

Le jeudi 16 avril 2015, Andrea Richiardi <notifications@github.com> a
écrit :

> Haven't they merge you patch for OSGi yet?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/735#issuecomment-93826942>.
>


-- 
Laurent Petit

**Comment by arichiardi** [comment]
Ok I checked REPL features and it looks good!
I correctly see:

    !MESSAGE Counterclockwise dependencies:
        [bultitude "0.2.1"]
        [ccw/ccw.server "0.1.1"]
        [ccw/clojure-ccw "1.7.0-03"]
        [cheshire "5.0.2"]

**Comment by arichiardi** [comment]
Laurent, when I launch a Repl with cider plugin, I still see:

```-- update-in :dependencies conj "[ccw/ccw.server \"0.1.1\"]" -- update-in :injections conj "(require 'ccw.debug.serverrepl)"```

I don't know if it is on purpose, I thought I'd better signal it.

**Pull request merged**
