### PR TITLE
Tracing

### PR DESCRIPTION
**Pull request by laurentpetit**
- Refactoring of code
- Every trace option has documentation
- cross reference between `.options` and `TraceOptions.java` files
- `ccw.core/log/trace` has been renamed to the more conventional (in Eclipse world) `ccw.core/debug`

See #743

### CODE REVIEW

**Comment by laurentpetit** [comment]
@arichiardi here it is, a decent commit. Did not have time to test, but it was either just that now, or a fully tested PR but in an uncertain future.

**Comment by arichiardi** [comment]
BTW, I think that if you clone my branch and add commits to it they will show up in the other PR, I am going to try with this.. :)

**Comment by arichiardi** [comment]
In this branch I now get the following error with the standalone product:

    Error loading refactor-nrepl.middleware: java.io.FileNotFoundException: Could not locate clojure/java/classpath__init.class or clojure/java/classpath.clj on classpath: , compiling:(refactor_nrepl/ns/slam/hound/search.clj:1:1)

**Comment by laurentpetit** [comment]
How / when is this error triggered ?

**Comment by arichiardi** [comment]
Yes, sorry, when either I launch a headless Repl or Load a file in Repl.

**Comment by arichiardi** [comment]
It might be in my conf , because now it happens in any branch. What can it be? here is the command line if it can help to figure out...really really weird...

    Launched process with command line: /usr/lib/jvm/java-8-oracle/bin/java -agentlib:jdwp=transport=dt_socket,suspend=y,address=localhost:55269 -Dccw.repl.launchid=9d078bd1-99c5-4fae-8a78-a8493597dded -client -Xbootclasspath/a:/home/kapitan/git/ccw/ccw.product/target/products/counterclockwise-0.31.2-SNAPSHOT/plugins/ccw.core_0.31.2.201504201717/leiningen-standalone.jar -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Dfile.encoding=UTF-8 -Dmaven.wagon.http.ssl.easy=false -classpath /home/kapitan/git/ccw/ccw.product/target/products/counterclockwise-0.31.2-SNAPSHOT/plugins/ccw.core_0.31.2.201504201717/leiningen-standalone.jar:/home/kapitan/git/ccw/ccw.product/target/products/counterclockwise-0.31.2-SNAPSHOT/plugins/ccw.core_0.31.2.201504201717/lein clojure.main -m ccw.leiningen.main update-in :jvm-opts concat "[\"-Xdebug\" \"-Xrunjdwp:transport=dt_socket,server=y,suspend=n\"]" -- update-in :dependencies conj "[ccw/ccw.server \"0.1.1\"]" -- update-in :injections conj "(require 'ccw.debug.serverrepl)" -- update-in : dissoc :main -- repl :headless

**Comment by laurentpetit** [comment]
So we can consider this PR ok ? If you have remarks to do on the code, you're welcome as well

**Comment by arichiardi** [comment]
It it interesting to ask why you now throw RuntimeExceptions in the NullTracer, isn't it just a pass-through when you do not need tracing?

Note: I have not dogged in the code...

I guess now we can replace all of the prn/println with trace...good luck to both eh eh

**Comment by arichiardi** [comment]
Neither Dogged, nor Digged ... :)

**Comment by laurentpetit** [comment]
Wow good catch for the send of RuntimeExceptions, I'll take a closer look, it does not feel right if it's doing this indeed

**Comment by arichiardi** [comment]
It looks like it is immediately caught inside the try/catch though..I cannot understand why I cannot comment lines in these...

**Comment by laurentpetit** [comment]
Well, in the last version of the NullTracer, I now just do ... nothing. Maybe you're looking at an intermediate commit instead of the full diff for the PR?

**Comment by laurentpetit** [comment]
OK, already switched a lot of printlns to traces. More TBD ...

**Comment by laurentpetit** [comment]
(not pushed yet, 'coz not tested)

**Comment by arichiardi** [comment]
You mean, we should add tests?

**Comment by arichiardi** [comment]
Aaah now it's clear :) You mean from your machine :)

**Comment by laurentpetit** [comment]
switched a lot of clojure code to traces instead of printlns. Hope I have not introduced regressions. I just found one error that I fixed, while testing the code.

**Comment by arichiardi** [comment]
I code reviewed it and it looks good, I will also test it as there might be some dynamic error not visible now...are tests working? In my patch I have added some but I had some red in ccw.core.test..I need to check that as well..

**Comment by laurentpetit** [comment]
WRT code review: thanks! Please report back again here if your live tests don't show anything. My mouse is over the `Merge` button, waiting for your Go ;-)

**Comment by arichiardi** [comment]
I teted the classic, open/close, load repl, evaluate some code, everything looks ok! (and I would like you to have a look at my ```hover-step1``` :) )

**Comment by laurentpetit** [comment]
Yes yes, sorry. I wanted to first finish what I had started, coz I'm fighting my bad habit of starting things and not finishing them ;)

I will merge the branch then, and continue looking at the hovers PR. yes, continue, since I have already reviewed its first commit which seems ok to me !

**Comment by arichiardi** [comment]
That's good! Don't worry Laurent, it is good to finish ```first``` and then ```fnext``` on the other tasks. Ok...I might have been using too much Clojure lately :dancer:

**Comment by laurentpetit** [comment]
;)

**Pull request merged**
