### PR TITLE
Better calls to Display sync / async exec both from java & clojure

### PR DESCRIPTION
**Pull request by laurentpetit**
Extracted from #815 (only the first commit).
Expect further improvements upon the first commit.

### CODE REVIEW

**Comment by arichiardi** [comment]
Ok, good! I will add explicit display param and remove ```workbench-display```

**Comment by laurentpetit** [comment]
please don't. I was brainstorming, we can sleep more on this.

**Comment by arichiardi** [comment]
Ok! hammock time on github is difficult to employ :smile: I will work on the folding part.

**Comment by laurentpetit** [comment]
If the 2 commits I added feel ok, I can merge this PR.

**Comment by arichiardi** [comment]
Sure, go ahead :+1:

**Comment by arichiardi** [comment]
Laurent, I am having a problem...I think is some older commit...

selection_023

Is it just me? I am bisecting to see which commit...

**Comment by laurentpetit** [comment]
I had this also today, what mess did I do .... -:-/

**Comment by laurentpetit** [comment]
OK, already found 2 bad uses of `ccw.swt/ui` in `ccw.repl.view-helpers` . Fixed and pushed.

**Comment by arichiardi** [comment]
Ok trying.

**Comment by arichiardi** [comment]
Still no decoration here...

**Comment by laurentpetit** [comment]
for the, the decoration comes an goes, dependening on I don't know what. for small files I have no problems.

**Comment by arichiardi** [comment]
very weird...I will try to bisect again, as I took just a small amount of commits before...

**Comment by arichiardi** [comment]
maybe some dependency changed...still cannot see it correctly, I will give it a break for now..

**Pull request merged**
