### PR TITLE
Add Test Generator menu and fixtures for it

### PR DESCRIPTION
**Pull request by arichiardi**
From the first comment:
```
This patch enables the user to record tests using the SWTBot generator and therefore ease the pain
    of bug reporting. It is also useful for debugging purposes and/or test enhancing.
    A contributed menu entry called "Generator..." in the Test menu will open the SWTBot interface. In
    the process, the MANIFEST.MF has been updated with the new version of SWTBot and updates it with the
    dependencies taken from the SWTBot samples. Hamcrest imports were also needed. Tests were added.
    
    Note1: the Clojure menu is always shown now because the user might want to call Test Generator even
    when the active part is not the ClojureEditor.
    Note2: the patch also performs a little refactoring of the command contributions
```

--

Hello Laurent, the honey is in Clojure -> Test -> Generator... but also in ```ccw.core.test``` :smile:  

<strike>I added a "mode" (which is enabled through -D option) where the user can record tests. Of course it would be great if we could have her project were to run the tests as well but at the beginning a sample project provided by us that can be imported in the workspace would suffice.
I also added ReplTests and tests for bug #817 so we really should merge this in :wink:<strike>

Not WIP anymore :+1:

### CODE REVIEW

**Comment by arichiardi** [comment]
Laurent have you see the error on the build? everything is fine on my machine but it looks like there is not enough space on the server...or there is some other Tycho problem...

**Comment by arichiardi** [comment]
Maybe [this is useful](https://stackoverflow.com/questions/4066424/java-lang-outofmemoryerror-java-heap-space-in-maven)

**Comment by laurentpetit** [comment]
Hi Andrea. Yes, I the problem is bogging me since yesterday. I have fixed locally the issue with the standalone product not working anymore (at least on OS x) since the move to Mars Stable. But indeed now it's the Jenkins server that refuses to build ...

I'll take a look at it ASAP, but alas not right now

**Comment by arichiardi** [comment]
Ok no problem, good that you have a solution already :+1:

**Comment by laurentpetit** [comment]
I will test this PR ASAP, seems really interesting !
Can you rebase it on top of the latest master?

**Comment by arichiardi** [comment]
done!

**Comment by arichiardi** [comment]
One test is failing here whereas it completes fine on my machine...is there a way by any chance to peek at ```ccw.core.test/target``` on the Trevis machine?

**Comment by laurentpetit** [comment]
no, not on the travis machine. On the jenkins machine, yes

**Comment by arichiardi** [comment]
Looks all green now!

**Comment by arichiardi** [comment]
Changed a lot of things, but some test are failing, I will need to fix them... a bit later...

**Comment by arichiardi** [comment]
Please have a look at the ```enhance BotUtils``` commit first as it adds/remove the things that we discussed: removing the system property (and Test Mode), adding the menu under ```Clojure > Test > Generator...``` removing ```then-```, explaining a bit more what the prefix are about, adding the copyright, improving ```ClojureEditorTests```...

**Comment by arichiardi** [comment]
All the test are green, it failed during the zip creation...I hope nothing too bad, I am going to check...

**Comment by arichiardi** [comment]
Apart from the small but important fixes, the build failed, again with that weird error while building the zips...

**Comment by laurentpetit** [comment]
It's probably because the new dependency is missing, maybe a repository or something like that. I can take care of this, I may be faster (I have done this a couple times already), and then let you review the issue (should be small) and I can explain you what I did in the comments

**Comment by arichiardi** [comment]
Deal! Tomorrow first thing I will fix these things..thanks as usual for the suggestions ;)

**Comment by laurentpetit** [comment]
OK. I may not be able to work on it before monday evening, tho.

**Comment by arichiardi** [comment]
Laurent, when you have time, could you attach the screen for the following?

```
!MESSAGE Change Clojure language support : Clojure language support successfully added for project my-second-clojure-project.

26 Jul 2015 10:40:48.387 -                      main - DEBUG -                       SWTUtils - (SWTUtils.java:405) - Capturing screenshot '/home/travis/build/laurentpetit/ccw/ccw.core.test/target/screenshots/updatesDependenciesOnceOnProjectCreation(ccw.core.SmokeTests).jpeg'
```

**Comment by laurentpetit** [comment]
Sorry, what do you mean ?

**Comment by arichiardi** [comment]
I would like to have a look at ```/home/travis/build/laurentpetit/ccw/ccw.core.test/target/screenshots/updatesDependenciesOnceOnProjectCreation(ccw.core.SmokeTests).jpeg``` as this test is succussful on my machine but not on the server and I don't understand why...

**Comment by laurentpetit** [comment]
sorry, but I have no access to this. It remains internal to the instance which is automatically discarded as soon as the build is stopped. The only way to do this would be to force it to ftp somewhere, but it's not active anymore since jenkins is pushing. Hmm, I'll try to reactivate again with a folder named differently.

**Comment by arichiardi** [comment]
Ah ok, well, about that test, it is weird it is not working... and maybe not even a screenshot can solve the mystery, but I figured I might give it a try...by the way it would be good to have the screenshot folder accessible for debugging future failing tests...

**Comment by laurentpetit** [comment]
OK, I've tweaked the old travis shell scripts so that hopefully they will publish their own qualified update sites (same qualifier as jenkins, but prepended with "travis").
Even in case of errors, the errors are published, as well as the directory containing screenshots !

**Comment by arichiardi** [comment]
Wow! I am going to try immediately! This address?
```https://github.com/laurentpetit/travis.ccw-ide.org```

**Comment by arichiardi** [comment]
Ah ok I have just noticed for the first time the page ```https://github.com/laurentpetit/jenkins.ccw-ide.org```...I am reading...

**Comment by laurentpetit** [comment]
Here for finding interesting stuff: http://updatesite.ccw-ide.org/branch/
Here is jenkins : https://jenkins.ccw-ide.org/

**Comment by arichiardi** [comment]
Lol, I don't know what you've done, but now the tests complete...all green!

**Comment by arichiardi** [comment]
I will start again just to be sure...

**Comment by arichiardi** [comment]
I removed a delay and now everything seems smooth, I think we can merge this one...if nothing else needs corrections..

**Comment by arichiardi** [comment]
Ok still the zip failing but I leave that to you :smile:

**Comment by arichiardi** [comment]
On Jenkins they are still failing, with screenshots in ```/var/lib/jenkins/jobs/ccw-master/workspace/ccw.core.test/target/screenshots/updatesDependenciesOnceOnProjectCreation(ccw.core.SmokeTests).jpeg```
Maybe it would be good to have some sort of access to it...what is the difference between Travis build and Jenkins build?

**Comment by arichiardi** [comment]
[Here](http://jenkins-ci.361315.n4.nabble.com/SWTBot-td4680130.html) they also have another idea, to use the vnc plugin in order to access to the display from remote...nice!

**Comment by laurentpetit** [comment]
on jenkins the failed tests should be published where the udpatesite would have been deployed. So maybe this has been disabled and I need to check why and whether it's easy to fix or not

**Comment by laurentpetit** [comment]
I did an update to the script. Let's see how it goes

**Comment by laurentpetit** [comment]
Here's one exception on travis : http://updatesite.ccw-ide.org/branch/master/travisCI000447-master-gitfc9437909edff55b7457c96e88eb370b331bcafb/ERROR-luna-openjdk7/ccw.core.SmokeTests.txt

No screenshot though :-(

**Comment by arichiardi** [comment]
Mmm...that error is weird, basically it cannot find the File menu...weird that we cannot see the screenshot as well...

Usually when it cannot find  a menu entry it means that some other window has focus (or some other software on the display)...today i am travelling and i won't be able to debug...note that all these tests are working both with mvn clean install and within Eclipse here...

**Comment by laurentpetit** [comment]
I tried an improvement. To be continued ...



—
Envoyé avec Mailbox

**Comment by arichiardi** [comment]
I think that if it fails and you have/want/think is a good idea...we can expose the display with vnc.

**Comment by laurentpetit** [comment]
Yeah, we'll have to try the vnc thing.

What annoys me is that with the current setup, the screenshots should be
published via ftp, as they are currently (successfully) for jenkins builds.

2015-07-27 8:55 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> I think that if it fails and you have/want/think is a good idea...we can
> expose the display with vnc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/816#issuecomment-125106457>.
>



-- 
Laurent Petit

**Comment by laurentpetit** [comment]
I will only be able to work on it this evening.

2015-07-27 9:02 GMT+02:00 Laurent PETIT <laurent.petit@gmail.com>:

> Yeah, we'll have to try the vnc thing.
>
> What annoys me is that with the current setup, the screenshots should be
> published via ftp, as they are currently (successfully) for jenkins builds.
>
> 2015-07-27 8:55 GMT+02:00 Andrea Richiardi <notifications@github.com>:
>
>> I think that if it fails and you have/want/think is a good idea...we can
>> expose the display with vnc.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/laurentpetit/ccw/pull/816#issuecomment-125106457>.
>>
>
>
>
> --
> Laurent Petit
>



-- 
Laurent Petit

**Comment by laurentpetit** [comment]
I don't understand. By reading the build logs on the travis console, it seems like there's no screenshots directory at all. I fixed a problem with the embedded ansi-repl plugin anyway, and I also simplified the travis script.
Somehow, those tests seem to be fragile, sometimes working, sometimes not, depending on some race conditions ...

**Comment by laurentpetit** [comment]
Look here, this is kinda proof that the build was unable to create any screenshot: https://travis-ci.org/laurentpetit/ccw/builds/72915194#L6685

**Comment by laurentpetit** [comment]
the tests don't pass on my machine. Somehow it seems like one of the tests is created twice, when the first instance has not been deleted. Weird.

**Comment by laurentpetit** [comment]
but the zips were created successfully. Trying the OS X version and reporting back in a while.

**Comment by laurentpetit** [comment]
The OS X version is working. But since the tests fail, I cannot (yet) incorporate it.
BTW, I did some tests, and it seems that SWTBot fails to record a lot of things, e.g. when the user double clicks to open a file in the editor, the cursor position, the current selection, content assist trigger. When in the REPL input area, each insert of a character creates a line in SWT which replaces the whole text, when clicking on Ctrl+Enter, nothing is generated, etc.

**Comment by arichiardi** [comment]
Strange, it should be fully reproducible...ok I will try again tomorrow when I will come back from my trip ok? I saw them all green a couple of times, but it is true, it looks like they are architecture/Eclipse version/moon dependent...

**Comment by laurentpetit** [comment]
ahah :-)

**Comment by arichiardi** [comment]
:smile: Well I'll say planet dependent and I am including Eclipses and real ones :smile_cat: :smiley:

**Comment by arichiardi** [comment]
Just rebased on master...

**Comment by arichiardi** [comment]
Incredible, I don't know what goes wrong...but look...almost at the same time as the Travis built...

selection_027

**Comment by arichiardi** [comment]
If you check the [last build](https://travis-ci.org/laurentpetit/ccw/builds/73238007) the failure is:

```[INFO] --- mojo-executor-maven-plugin:2.2.0:execute-mojo (archive) @ ccw.product ---

[INFO] Building zip: /home/travis/build/laurentpetit/ccw/ccw.product/target/products/ccw-linux.gtk.x86_64.zip

/home/travis/build.sh: line 41: 16425 Killed                  mvn clean verify --batch-mode -e -DforceContextQualifier=${QUALIFIER}

The command "mvn clean verify --batch-mode -e -DforceContextQualifier=${QUALIFIER}" exited with 137.```

**Comment by laurentpetit** [comment]
It's probably a memory problem. I think the old architecture of travis
where the build is currently forced to build (*) does not have enough
memory.

(*): on the new docker-based architecture, there's more memory & CPU
available per build process. But it is also more constrained, e.g. we
cannot sudo inside it, thus we cannot install the missing pieces for
launching the UI tests : sudo apt-get install xfvc metacity

Seems like we're out of luck on travis atm : it can build & launch tests on
the old architecture, but not create the standalone products. And it can
build & deliver products on the new (or so I hope), but not launch tests

2015-07-29 20:45 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> If you check the last build
> <https://travis-ci.org/laurentpetit/ccw/builds/73238007> the failure is:
>
> ```[INFO] --- mojo-executor-maven-plugin:2.2.0:execute-mojo (archive) @
> ccw.product ---
>
> [INFO] Building zip:
> /home/travis/build/laurentpetit/ccw/ccw.product/target/products/ccw-linux.gtk.x86_64.zip
>
> /home/travis/build.sh: line 41: 16425 Killed mvn clean verify --batch-mode
> -e -DforceContextQualifier=${QUALIFIER}
>
> The command "mvn clean verify --batch-mode -e
> -DforceContextQualifier=${QUALIFIER}" exited with 137.```
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/816#issuecomment-126055075>.
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
Yes [this](http://updatesite.ccw-ide.org/branch/swtbot-generator/travisCI000451-swtbot-generator-gitf84301dcf7ea17aca1121fd84e3d782abe85ef3b/ERROR--openjdk7/) confirms all the tests went smoothly. So no way to get the screen on Jenkins' machine?

**Comment by laurentpetit** [comment]
Problem with the jenkins machine is that I haven't yet configured it to
work with any Pull Request. So it will build everything you, I and
Christophe push since we push to laurentpetit/ccw, but not things pushed to
forks.
But on Jenkins, I thought the screenshots, when problems occur, where OK,
weren't they?

2015-07-29 21:19 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> Yes this
> <http://updatesite.ccw-ide.org/branch/swtbot-generator/travisCI000451-swtbot-generator-gitf84301dcf7ea17aca1121fd84e3d782abe85ef3b/ERROR--openjdk7/>
> confirms all the tests went smoothly. So no way to get the screen on
> Jenkins' machine?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/816#issuecomment-126065287>.
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
Mmm...I checked [here](http://updatesite.ccw-ide.org/branch/swtbot-generator/) but nothing in sight...

**Comment by laurentpetit** [comment]
because all the jenkins builds went OK

2015-07-29 21:24 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> Mmm...I checked here
> <http://updatesite.ccw-ide.org/branch/swtbot-generator/> but nothing in
> sight...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/816#issuecomment-126067283>.
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
The last build you mean? Aren't the tests always failing...maybe I am looking at the wrong place :confused:

**Comment by laurentpetit** [comment]
BTW, I'm cutting a stable release right now !

2015-07-29 22:58 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> The last build you mean? Aren't the tests always failing...maybe I am
> looking at the wrong place [image: :confused:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/816#issuecomment-126094052>.
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
Great, just as a side note, it looks like is doing something on failure:

!ENTRY ccw.core 1 0 2015-07-29 20:17:17.097
!MESSAGE reading in launchNameREPLURLPromiseAndWithREPLView the key: my-first-clojure-project Leiningen VM #1

!ENTRY ccw.core 1 0 2015-07-29 20:17:19.266
!MESSAGE Change Clojure language support : Clojure language support successfully added for project my-first-clojure-project.
[JENKINS] Recording test results
[JENKINS] Archiving disabled

**Comment by arichiardi** [comment]
By the way, is it that  Jenkins does not have SWTBot features?

For example, in my own test launcher I have to install it with:
```
$DIRECTOR_LOCATION/director \
     -destination $ECLIPSE_DIR \
     -repository $SWTBOT_SITE \
     -installIU org.eclipse.swtbot.junit4_x \
     -installIU org.hamcrest.core
```
Maybe a little difference in the scripts with Travis? Maybe one has the swtbot feature, the other one doesn't (testing the plugin only?)

**Comment by laurentpetit** [comment]
Jenkins does need to "have" SWTBot features. The maven Tycho plugin
normally takes care of everything.
When launching from Eclipse (and not maven), things are different. But I
must admit it's been a while (maybe a month) since I haven't ran tests but
from the command line, so.

2015-07-30 8:43 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> By the way, is it that Jenkins does not have SWTBot features?
>
> For example, in my own test launcher I have to install it with:
>
> $DIRECTOR_LOCATION/director \
>      -destination $ECLIPSE_DIR \
>      -repository $SWTBOT_SITE \
>      -installIU org.eclipse.swtbot.junit4_x \
>      -installIU org.hamcrest.core
>
> Maybe a little difference in the scripts with Travis? Maybe one has the
> swtbot feature, the other one doesn't (testing the plugin only?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/816#issuecomment-126202923>.
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
No but my ```SUCCESS``` comes from ```mvn clean install``` and I cannot understand why Travis succeeds and Jenkins no...

**Comment by laurentpetit** [comment]
Isn't it the contrary? jenkins succeeding, and travis failing?

2015-07-30 12:07 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> No but my SUCCESS comes from mvn clean install and I cannot understand
> why Travis succeeds and Jenkins no...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/816#issuecomment-126259559>.
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
No but Jenkins tests are not succeeding, even if the build does. Travis fails building because of the memory issue..at least this is what I see from here (the big red Xs below)

**Comment by arichiardi** [comment]
I am talking about [this Jenkins branch](http://updatesite.ccw-ide.org/branch/swtbot-generator/)

**Comment by arichiardi** [comment]
Going back to this:

 - about Travis: couldn't we provide an already made docker image and upload it, which will contain the software that we need (sorry I have not investigated myself).
 - about Jenkins: I am sure there is some config problem as it does not make sense that it fails this way ([branch]([this Jenkins branch](http://updatesite.ccw-ide.org/branch/swtbot-generator/)).

**Comment by arichiardi** [comment]
What about [this](https://circleci.com/docs/environment) ?

**Comment by laurentpetit** [comment]
looks promising !

2015-07-31 16:26 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> What about this <https://circleci.com/docs/environment> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/816#issuecomment-126708247>.
>



-- 
Laurent Petit

**Comment by laurentpetit** [comment]
I see that their first container is free.
If only travis containers allowed, or provided out of the box, xvfb, it
would also be easy to make another try on their docker infrastructure ...

2015-07-31 16:30 GMT+02:00 Laurent PETIT <laurent.petit@gmail.com>:

> looks promising !
>
> 2015-07-31 16:26 GMT+02:00 Andrea Richiardi <notifications@github.com>:
>
>> What about this <https://circleci.com/docs/environment> ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/laurentpetit/ccw/pull/816#issuecomment-126708247>.
>>
>
>
>
> --
> Laurent Petit
>



-- 
Laurent Petit

**Comment by laurentpetit** [comment]
I re-read the travis doc, and there's some hope that we can do UI tests in
the container-based architecture.
I'll test this this week-end !

2015-07-31 16:34 GMT+02:00 Laurent PETIT <laurent.petit@gmail.com>:

> I see that their first container is free.
> If only travis containers allowed, or provided out of the box, xvfb, it
> would also be easy to make another try on their docker infrastructure ...
>
> 2015-07-31 16:30 GMT+02:00 Laurent PETIT <laurent.petit@gmail.com>:
>
>> looks promising !
>>
>> 2015-07-31 16:26 GMT+02:00 Andrea Richiardi <notifications@github.com>:
>>
>>> What about this <https://circleci.com/docs/environment> ?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/laurentpetit/ccw/pull/816#issuecomment-126708247>.
>>>
>>
>>
>>
>> --
>> Laurent Petit
>>
>
>
>
> --
> Laurent Petit
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
Great! Just as a side note, [Xephyr](https://stackoverflow.com/questions/29509868/running-xephyr-inside-a-docker-container) also works for SWTBot (I am using it on my linux machine).

**Comment by laurentpetit** [comment]
ok, noted

2015-07-31 16:47 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> Great! Just as a side note, Xephyr
> <https://stackoverflow.com/questions/29509868/running-xephyr-inside-a-docker-container>
> also works for SWTBot (I am using it on my linux machine).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/816#issuecomment-126713060>.
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
I have rebased on ```master``` and about to try if tests are green on my machine after the new release!

**Comment by arichiardi** [comment]
I had to remove one test, because when you send the updates to background then you cannot check if the dialog exists any more (the problem of only one Eclipse instance)...now all green!

**Comment by arichiardi** [comment]
On the Jenkins machine still red...if you can access to ```/var/lib/jenkins/jobs/ccw-master/workspace/ccw.core.test/target/screenshots/canOpenRepl(ccw.core.ReplTests).jpeg``` I will be a happy dev :smile:

**Comment by arichiardi** [comment]
I grabbed the image below from the failing tests, and it looks like they are being executed in parallel...one on top of each other...I am investigating on how to disable this.

ccw core repltests

**Comment by arichiardi** [comment]
Rebased on master and fixed a problem (hard to find in the docs, I had to scrap ```surefire``` and ```tycho```). Basically no SWTBot code must go in ```@AfterClass``` and ```@BeforeClass```. I hope it will solve on Jenkins as well...

**Comment by laurentpetit** [comment]
crossing fingers

2015-08-14 11:24 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> Rebased on master and fixed a problem (hard to find in the docs, I had to
> scrap surefire and tycho). Basically no SWTBot code must go in @AfterClass
> and @BeforeClass. I hope it will solve on Jenkins as well...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/816#issuecomment-131041495>.
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
Alllll green again. I guess now this can be merged.

**Comment by laurentpetit** [comment]
I can't make the tests pass here.
Sometimes it says that there's an existing project already there, and is
stuck.
I also kind of saw that it was missing the java library, the projects
remain with 2 problem errors each time (even though this is not tested and
would not fail the tests, this is weird).

2015-08-14 12:02 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> Alllll green again. I guess now this can be merged.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/816#issuecomment-131056736>.
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
Mmmm...very weird, I will try launching Travis again...as I might just have been lucky...

**Comment by arichiardi** [comment]
Travis kind of goes through with it...I see all green again...maybe the problem is with the new ```lein``` changes you're working on (just guessing) ?

**Comment by laurentpetit** [comment]
no no, used your plain branch

2015-08-14 16:44 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> Travis kind of goes through with it...I see all green again...maybe the
> problem is with the new lein changes you're working on (just guessing) ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/816#issuecomment-131131246>.
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
This is indeed very strange...dunno how else to help you from here...again, maybe there is some setting that I am missing that makes the test run in parallel, but I read a big deal about it and it should be disabled by default.
Have you tried to run them from within eclipse (debug configuration) ? Are they working like that?

**Comment by arichiardi** [comment]
Incredible here is all green...is it your machine and Jenkins Osx?
Maybe this test harness runs smoothly only on linux? On my machine tests are running fine...

**Comment by laurentpetit** [comment]
I merged the branch in master and pushed master. If things are fine for
travis, so will they for me.

2015-08-21 17:32 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> Incredible here is all green...is it your machine and Jenkins Osx?
> Maybe this test harness runs smoothly only on linux? On my machine tests
> are running fine...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/816#issuecomment-133463980>.
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
Lol, it really is the boss now :+1:

**Comment by arichiardi** [comment]
Mmm...I don't know if you've added the changes, I don't see all my little pictures on master :smile:

**Comment by laurentpetit** [comment]
Yes I have, or haven't I ?

**Comment by arichiardi** [comment]
Oh you did..maybe I am drunk :)
I am closing this one ok?

**Comment by arichiardi** [comment]
It is great now, we can add all the tests for new functionalities or past issue, I am happy aahahaha

**Comment by laurentpetit** [comment]
If you feel like adding a section on how to add tests on the CONTRIBUTING
file, that would be a great addition adding even more value to the feature
;-)

Le samedi 22 août 2015, Andrea Richiardi <notifications@github.com> a
écrit :

> It is great now, we can add all the tests for new functionalities or past
> issue, I am happy aahahaha
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/816#issuecomment-133637755>.
>


-- 
Laurent Petit

**Pull request closed without merging**
