### PR TITLE
fix(cider): cider-nrepl only loaded when embedded repl autostart is true

### LINKED ISSUE #768: Load `cider-nrepl` optionally for CCW JVM
This is important, because `cider-nrepl` namespace takes a long time to load (even when AOTed), so I don't want users to pay the price everytime they start the first REPL in a fresh Eclipse instance.

@arichiardi I'd like to make loading cider-nrepl handler for CCW internals off by default, since it takes up so much more time to load and most users won't benefit from it.

Tie it to the existing option to autostart the repl when CCW starts (because generally speaking, if one sets the autostart option, then one wants to connect to the repl for all batteries included)
thoughts?

### PR DESCRIPTION
**Pull request by laurentpetit**
Fixes #768

### CODE REVIEW

**Comment by arichiardi** [comment]
Just bumped ```org.clojure/tools.nrepl```, and tested, good to go.

**Comment by arichiardi** [comment]
Can I merge my first PR :blush: ?

**Comment by laurentpetit** [comment]
Sure! ;)

**Comment by laurentpetit** [comment]
:+1:

**Pull request merged**
