### PR TITLE
Doc rework

### PR DESCRIPTION
**Pull request by laurentpetit**

### CODE REVIEW

**Comment by laurentpetit** [comment]
@arichiardi FYI I did a pass on the documentation. Interestingly I have been incited to work on this as a digression while reviewing the tests PR :-)

**Comment by arichiardi** [comment]
Wooo, ok I will check that's great, I was thinking of adding a page on the hovers actually..

**Comment by laurentpetit** [comment]
Sure, that would be great!

**Comment by arichiardi** [comment]
I have the following with ```mvn clean compile```:

    Plugin org.asciidoctor:asciidoctor-maven-plugin:1.5.2 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.asciidoctor:asciidoctor-maven-plugin:jar:1.5.2: Could not transfer artifact org.asciidoctor:asciidoctor-maven-plugin:pom:1.5.2 from/to tycho (https://oss.sonatype.org/content/groups/public/): oss.sonatype.org: unknown error: Unknown host oss.sonatype.org: unknown error -> [Help 1]

**Comment by arichiardi** [comment]
Compile and checked the new shiny TOC, nice :)

**Pull request merged**
