### PR TITLE
Hovers step1 reviewed + atom fix

### PR DESCRIPTION
**Pull request by arichiardi**
Hello Laurent,
this is the part already reviewed, rebased.

Today I have (hopefully) implemented the state/atom part correctly and, if you have time, I'd like you to have a look at it: I basically have encapsulated my state in a single atom called ```State```.
From there I fixed some other parts that I had already done and were part of my ```color-refactoring``` branch.

I am still not happy with some part of it. I would like to still push some commit in the next couple of days. Not perfect yet.

### CODE REVIEW

**Comment by laurentpetit** [comment]
Maybe I'll let you do everything you had in mind before looking at the code more globally (not even sure I'll have the time to do an architecture review, so as long as it works, and it does not spread through all the codebase, I'm fine with what you'll end with)

**Comment by arichiardi** [comment]
I am trying to reapply all the things I had in that branch, fixing if I see something brittle. For example, the State atom. I also refactored [big time](https://github.com/arichiardi/ccw/commit/4e345e8b7204b53b807990d0fdabfb65b37c7ea2) in ```color-refactoring``` branch...I don't know if it is something worth it now, but it gave me the compos-ability necessary to fix a couple of long-standing (from your comments) problems.

**Comment by arichiardi** [comment]
Merged all the things I had in ```color-refactoring``` !!!

**Comment by laurentpetit** [comment]
Cool ! Give me the go when you stop working on the PR. I will look at it, tomorrow I think (I won't have large enough chunks of time for it today)

**Comment by arichiardi** [comment]
I have finished for now, note that here:

1) I did not extracted the coloring fixes (I have a separate local rebate for that)
2) Once merged, I will start adding more hovers, at the moment just docstring is in, like before

I wanted to finish by Thursday :))

**Comment by laurentpetit** [comment]
I don't understand what you mean in point 1) ?

Le mercredi 6 mai 2015, Andrea Richiardi <notifications@github.com> a
écrit :

> I have finished for now, note that here:
>
> 1) I did not extracted the coloring fixes (I have a separate local rebate
> for that)
> 2) Once merged, I will start adding more hovers, at the moment just
> docstring is in, like before
>
> I wanted to finish by Thursday :))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/756#issuecomment-99423558>.
>


-- 
Laurent Petit

**Comment by arichiardi** [comment]
Ups..Sorry, I wanted to say that this patch includes hover things only and that I will open another PR isolating the color fixes without too much refactoring...

**Comment by laurentpetit** [comment]
Quickly reviewed the code, seems good, will test it ASAP

**Comment by laurentpetit** [comment]
Ok, I tested the feature.
I appreciate the improvements in the HTML layouting !
I have also some remarks :-)

- The docstring hover was not enabled by default. This will surprise everybody if we can't fix this
- The location and meaning of the `Choose a key modifier for` group is very strange. It takes up a lot of vertical space, and displays the same information as what is in the table. I would just go with the table. Or at least make it clearer that it is a "master / detail" view, and maybe have the "detail" display below the table. But really, just not displaying the "detail" and just have the table would be clearer and simpler.

**Comment by arichiardi** [comment]
Let's just leave the table then, and I fill fix point 1.

**Comment by arichiardi** [comment]
*will

**Comment by arichiardi** [comment]
About the table, I have a re-remark :)
I wanted to show it like that as it is not always easy to see what is it in the description part. In JDT the descriptions of the hovers are long and I though to follow their design.
Maybe put it below improves the situation, shall we try?

**Comment by laurentpetit** [comment]
Yes

2015-05-07 16:12 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> About the table, I have a re-remark :)
> I wanted to show it like that as it is not always easy to see what is it
> in the description part. In JDT the descriptions of the hovers are long and
> I though to follow their design.
> Maybe put it below improves the situation, shall we try?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/756#issuecomment-99881841>.
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
Boom, when you sent "Yes" over the network I pushed my change :)
It looks way better actually. I'd leave it like that unless you have other improvements.

**Comment by laurentpetit** [comment]
I know what is a little bit surprising : when arriving to the Hovers
Preference Page, if there is at least one hover (and there will be 100% of
the cases) in the list, then the first one should be selected, so that the
"detail" view is not empty and the user (me) can understand the link
between the 2.
Else, The user is left with the feeling that there's a bug in the UI :
there is a blank input text floating in the middle of the page.

Another remark: it seems like there's a regression in the "namespace
browser" : if you hover over a public definition of a var, e.g.
`clojure.core/map`, then one can see `nbsp` and `<pre>` and `</pre>`
printed on the first lines near arglist definition

2015-05-07 16:19 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> Boom, when you sent "Yes" over the network I pushed my change :)
> It looks way better actually. I'd leave it like that unless you have other
> improvements.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/756#issuecomment-99883320>.
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
Ok, I can solve them...and...thanks for testing :)

**Comment by arichiardi** [comment]
I do I show things in the ```Namespace Browser``` ? Mine is empty ?!

**Comment by laurentpetit** [comment]
You also have a repl open?

Le jeudi 7 mai 2015, Andrea Richiardi <notifications@github.com> a écrit :

> I do I show things in the Namespace Browser ? Mine is empty ?!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/756#issuecomment-99980557>.
>


-- 
Laurent Petit

**Comment by arichiardi** [comment]
Done, fixed and improved ;)
When you give me the nod, I will squash, rebase, merge, jump and flip in the air, whistle and push!

**Comment by arichiardi** [comment]
Sorry this last bug I fixed was because it is late :) I think that's it for me for today.

**Comment by arichiardi** [comment]
I swear this is the last one, I am going to go to sleep...there was a little glitch showing too many ```\n``` in case of empty sections in ```doc_utils.clj``` and I could not avoid fixing it :smile:

**Comment by laurentpetit** [comment]
Can  you just rebase? Because since there is still the `cider-nrepl` moving target with its changing dependencies, it's a pain to have to `mvn clean verify` and waiting for several minutes when switching between branches. Thx.

**Comment by arichiardi** [comment]
Of course, BTW if usually mvn clean compile and it is usually quicker

**Comment by laurentpetit** [comment]
ah indeed.

2015-05-08 13:51 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> Of course, BTW if usually mvn clean compile and it is usually quicker
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/756#issuecomment-100208569>.
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
Done! I will of course squash again after your go.

**Comment by laurentpetit** [comment]
Hello, some additional remarks:

- in the namespace browser: tooltips for namespaces with no documentation show 2-3 additional blank lines
- in the namespace browser: tooltips for namespaces with documentation have lots of blank lines between the first line and the documentation line
- in editors: dunno why it's so, but it seems that the last line of content is systematically not shown. Especially annoying when the docstring has only one line and one cannot see it without using mouse / wheel to scroll the content.

**Comment by arichiardi** [comment]
Ok I am going to check.

**Comment by arichiardi** [comment]
If you can find it, can you give an example of point 2 in ```clojure.core```?

**Comment by laurentpetit** [comment]
- For point 2: the tooltip for `clojure.core` ns itself, not for vars inside the namespace

**Comment by arichiardi** [comment]
Look perfect

**Comment by arichiardi** [comment]
For point 3, here is a screenshot, again if you have time I would like to have an example because I cannot reproduce it:

selection_006

**Comment by laurentpetit** [comment]
Weird. Let's say it's ok, and if it is still an issue when everything is
merged, etc., it will not be too late to fix this minor issue

Le vendredi 8 mai 2015, Andrea Richiardi <notifications@github.com> a
écrit :

> For point 3, here is a screenshot, again if you have time I would like to
> have an example because I cannot reproduce it:
>
> [image: selection_006]
> <https://cloud.githubusercontent.com/assets/1724788/7536924/bba3e8e2-f594-11e4-90b5-d71db987d7ea.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/756#issuecomment-100227464>.
>


-- 
Laurent Petit

**Comment by arichiardi** [comment]
Agree

**Comment by laurentpetit** [comment]
Sure, go go ! ;-)

**Comment by arichiardi** [comment]
Done!

**Comment by arichiardi** [comment]
Ok I will amend the comment from conflicts that cherry pick added and then we are ready to merge!

**Comment by arichiardi** [comment]
Now I see the problem with the last line, let me just quickly try to fix it :smile:

**Comment by arichiardi** [comment]
Ok fixed and already rebased, now it should always show the last line.

**Comment by laurentpetit** [comment]
Ahh, this depends on the size of the font. I have the `ccw-plugin-zoom` enabled, and frequently play with `Ctrl+ + ` `Ctrl+ - ` to adapt the font size. Recently I was on a large font size. When I switch back to a small font size, I don't see the problem.

**Comment by arichiardi** [comment]
Great, I think I will maintain these commits as they also describe what I have done :+1:

**Comment by laurentpetit** [comment]
OK! So I'll merge the PR! Champaign! :-)

**Comment by arichiardi** [comment]
:dancer: :dancers:

**Comment by arichiardi** [comment]
I wanted to ask you, can you point me to the place where you set the font for CCW, I have a couple of ideas...or maybe I should just have a look at the zoom user plugin?

**Comment by laurentpetit** [comment]
CCW just uses the default fonts, as far as I remember. You're right that having a look at the zoom user plugin could provide some more background

**Pull request merged**
