### PR TITLE
Remove modal Popup when REPL asks for input on *in*

### PR DESCRIPTION
**Pull request by laurentpetit**

### CODE REVIEW

**Comment by laurentpetit** [comment]
@arichiardi This is one interesting: it inlines calls to e.g. `(read-line)` in the normal input area of the REPL. Thus there's no modal popup anymore which blocked the Eclipse UI.

**Comment by arichiardi** [comment]
Great, in my Preference page I started adopting org.eclipse...databinding, it is great that we are passing to some more reactive UI. I will test both patches.

**Comment by laurentpetit** [comment]
yes, I also need to get some more official eclipse traces in my toolbox!

**Comment by laurentpetit** [comment]
Hey @arichiardi, have you have some time to test or review this small PR ?

**Comment by arichiardi** [comment]
trying now ;)

**Comment by arichiardi** [comment]
Yep tried, works! A suggestion, if it is feasible, would be to output some sort of "waiting for input" in the repl area, and a "cancel input wait" (that can be a normal "Cancel last evaluation") if one wants to do something else, but the latter option maybe is not urgent as a simple input in the area would proceed in any case.

**Comment by laurentpetit** [comment]
There is a waiting for input, if the focus is not yet in the input area.
Maybe we could change the area's background color or border color ?

Le mercredi 22 avril 2015, Andrea Richiardi <notifications@github.com> a
écrit :

> Yep tried, works! A suggestion, if it is feasible, would be to output some
> sort of "waiting for input" in the repl area, and a "cancel input wait"
> (that can be a normal "Cancel last evaluation") if one wants to do
> something else, but the latter option maybe is not urgent as a simple input
> in the area would proceed in any case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/747#issuecomment-95227001>.
>


-- 
Laurent Petit

**Comment by arichiardi** [comment]
Good idea, I like it.

**Comment by laurentpetit** [comment]
OK, I have reworked it so your remarks are taken into account (hopefully).

Now there are 2 separate TextViewers for code input and `*in*` input, they are placed inside a `StackLayout` and switched appropriately.
The `stdinStyledText` gets a retro style with gray background and dark green foreground (reminding me of old terminals).

**Comment by arichiardi** [comment]
Checking!

**Comment by arichiardi** [comment]
Great, it works! I would darken the background as you don't notice it too much

**Comment by laurentpetit** [comment]
Ok I will and then merge into master, thanks for the quick feedback !

Le jeudi 23 avril 2015, Andrea Richiardi <notifications@github.com> a
écrit :

> Great, it works! I would darken the background as you don't notice it too
> much
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/747#issuecomment-95649856>.
>


-- 
Laurent Petit

**Comment by arichiardi** [comment]
I learned a lot of Clojure with the hover feature and I like it, I enjoyed the project and to give feedback is the minimum I can do to give my joy back :)

**Comment by laurentpetit** [comment]
Glad to read that :-)

**Comment by laurentpetit** [comment]
Done changing colors. Merging the PR in 3..2..1..0

**Comment by arichiardi** [comment]
Beautiful!

**Comment by laurentpetit** [comment]
Yes I preferred real black because it's when text is most visible, be it
selected or not.

Le vendredi 24 avril 2015, Andrea Richiardi <notifications@github.com> a
écrit :

> Beautiful!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/747#issuecomment-95834574>.
>


-- 
Laurent Petit

**Comment by arichiardi** [comment]
:+1:

**Pull request merged**
