### PR TITLE
Color refactoring and hover fixes

### PR DESCRIPTION
**Pull request by arichiardi**
*(Comprehends the other pull requests, from older to newer, if someone wants to help me testing these patches I have updated my [master](https://github.com/arichiardi/ccw) with all my recent ones.)*

Adds the ability of contributing and configuring ITextHover* instances to Counterclockwise.
The extension point is ccw.core.cljEditorTextHovers whereas the schema (a cousin of Jdt's) is
contained in schema/cljEditorTextHovers.exsd. Moreover, I basically created a layer of mixins for IClojureEditor and (the new) IClojureSourceViewer.

IClojureHover protocol has been introduced (see docstring_hover.clj for the usage). Second,
ccw.core/assets/hover-control-style.css is prepended to the displayed html in order to control the
output of HoverControlCreator and HoverEnrichedControlCreator.
Together with the above, the org.eclipse.ui.edit.text.showInformation action has been retargeted and
bound to IInformationPresenter/Provider which at the moment handles just one document partition and delegates to ITextHover instances the information retrieval.

Finally the preview in Clojure -> Colors and Fonts now reacts to changes in configuration and can be used to test the syntax coloring as well. The changes also propagate to the editors when OK/Apply is pressed.
Code wise, some ack was removed (due to initialization issues) both in previous code and in code in my other pull requests on for the hover framework (on which I built on and fixed something).

I refactored on my taste, but of course I am available for any discussion on the topic :+1: 
I hope I have decently cleaned up my patches.

### CODE REVIEW

**Comment by laurentpetit** [comment]
Would it be feasible to extract the "Color refactoring" into its own smaller Pull Request?

**Comment by arichiardi** [comment]
Hi Laurent, I have tried to pull out just that part, but it was a lot of work and I decided to leave it there...

**Comment by laurentpetit** [comment]
Ok, so just to double check: this PR #43 replaces PRs #40 and #42, so that I can safely close them, right?

**Comment by arichiardi** [comment]
Yes right

**Comment by laurentpetit** [comment]
Same request here: if you can create entr(y)(ies) to the ChangeLog.adoc file, please. Also, if there are breaking changes, or changes that could break things for users, please also add a mention of this just below the the version information, so that it's visible for the user before reading the detailed items.

**Comment by laurentpetit** [comment]
Hi, Can you check why the merge cannot be done automatically? Thanks!
I haven't started to review the code yet, so feel free to rebase your branch if you want.
But for the future, I think it would be best if, once discussions start, we stop rebasing and rewriting history, because it is painful for the reviewer to see what's changed in reaction to a discussion.
This doesn't prevent to do a last-moment commits "compression" (squash) before hitting the "Merge pull request", of course, once the discussions are over and the branch ready to be merged.

**Comment by arichiardi** [comment]
Roger that

**Comment by arichiardi** [comment]
Just a second, I am about to fix a little problem of the merge...

**Comment by laurentpetit** [comment]
ok

**Comment by arichiardi** [comment]
By the way, I had to change my compliance default to make it work, I have used some ArrayList<> given that our JDK is 1.7 but Eclipse needs to have the compliance set as well. We might consider changing it in the project itself (that means changing a .pref file).

**Comment by laurentpetit** [comment]
Yes, you can change it in the project itself.

**Comment by laurentpetit** [comment]
I tried the color-refactoring branch locally, and got this exception when trying to open a clojure file:

```java
java.lang.RuntimeException: EOF while reading
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.LispReader.read(LispReader.java:168)
	at clojure.lang.RT.readString(RT.java:1785)
	at clojure.core$read_string.invoke(core.clj:3650)
	at ccw.editors.clojure.hover_support$read_and_sanitize_descriptor_string.invoke(hover_support.clj:181)
	at ccw.editors.clojure.hover_support$read_descriptors_from_preference_BANG_.invoke(hover_support.clj:186)
	at ccw.editors.clojure.hover_support$configured_state_masks.invoke(hover_support.clj:518)
	at clojure.lang.Var.invoke(Var.java:383)
	at ccw.util.ClojureUtils.invoke(ClojureUtils.java:46)
	at ccw.util.ClojureInvoker._(ClojureInvoker.java:26)
	at ccw.editors.clojure.ClojureSourceViewerConfiguration.getConfiguredTextHoverStateMasks(ClojureSourceViewerConfiguration.java:142)
	at org.eclipse.jface.text.source.SourceViewer.configure(SourceViewer.java:507)
	at ccw.editors.clojure.ClojureSourceViewer.configure(ClojureSourceViewer.java:276)
	at org.eclipse.ui.texteditor.AbstractTextEditor.createPartControl(AbstractTextEditor.java:3427)
	at org.eclipse.ui.texteditor.StatusTextEditor.createPartControl(StatusTextEditor.java:54)
	at org.eclipse.ui.texteditor.AbstractDecoratedTextEditor.createPartControl(AbstractDecoratedTextEditor.java:447)
	at ccw.editors.clojure.ClojureEditor.createPartControl(ClojureEditor.java:240)
```

**Comment by arichiardi** [comment]
wow, ok I am going to check...

**Comment by arichiardi** [comment]
Ok I will fix it, for now try to put the following line in your ```*workspace*/.metadata/.plugins/org.eclipse.core.runtime/.settings/ccw.core.prefs```

```ccw.preferences.hover_descriptors=({\:modifier-string "", \:enabled true, \:id "ccw.editors.clojure.hovers.docstringHover"})```

**Comment by arichiardi** [comment]
Sometimes I cannot understand Eclipse...I swear it was working before, now I needed to fix some stuff in order to avoid compilation errors..anyway, now all green!

**Comment by laurentpetit** [comment]
new error saying that the browser repl cannot find namespace `clojure.java.data`

I had to locally add new jars from `ccw.core/lib/` in the java build path of the `ccw.core` Eclipse project, as well as in the Runtime tab of the `ccw.core/plugin.xml` PDE Editor

**Comment by arichiardi** [comment]
??? really strange...did you do a ```mvn clean compile``` before? it should download all the dependencies and put them in ```ccw.core/lib``` automatically.

**Comment by laurentpetit** [comment]
Yes I did.

The problem was mentions were missing in the .classpath file and in the
META-INF/MANIFEST.MF files.

2015-03-26 10:34 GMT+01:00 Andrea Richiardi <notifications@github.com>:

> ??? really strange...did you do a mvn clean compile before? it should
> download all the dependencies and put them in ccw.core/lib automatically.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/43#issuecomment-86421037>.
>



-- 
Laurent Petit

**Comment by laurentpetit** [comment]
I see that the PR doesn't merge anymore. Maybe I just let you make it work
again, and then test again from a fresh local branch.

2015-03-26 10:36 GMT+01:00 Laurent PETIT <laurent.petit@gmail.com>:

> Yes I did.
>
> The problem was mentions were missing in the .classpath file and in the
> META-INF/MANIFEST.MF files.
>
> 2015-03-26 10:34 GMT+01:00 Andrea Richiardi <notifications@github.com>:
>
>> ??? really strange...did you do a mvn clean compile before? it should
>> download all the dependencies and put them in ccw.core/lib automatically.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/laurentpetit/ccw/pull/43#issuecomment-86421037>.
>>
>
>
>
> --
> Laurent Petit
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
ok

**Comment by arichiardi** [comment]
I had indeed to rebase in order to fix a conflict in the pom.xml

**Comment by arichiardi** [comment]
A little bit messy but now it *should* be good to go.

**Comment by laurentpetit** [comment]
I see that java.data.jar and tools.logging.jar are not the in the ccw.core eclipse project java build path. Any reason for them not to be ?

**Comment by laurentpetit** [comment]
Also, `clj-tuple.jar`, `potemkin.jar`, `riddley.jar` and tools.reader.jar are in the `ccw.core/lib/` folder, but not referenced in the runtime `MANIFEST` for the plugin.

**Comment by laurentpetit** [comment]
Ok, I manage to start everything locally. I see some regressions, or so it seems. For instance, if I open a file, and a REPL, and try to hover my mouse over a println symbol, I don't see the documentation appear.

Also, if I place the caret at the end of the editor, and type an open parenthesis, the closing parenthesis is black instead of being colored.

**Comment by arichiardi** [comment]
About the first, be sure that the hover shortcut is blank in Preferences->Clojure->Editor->Hovers. This feature works like JDT, it allows to press a combination of keys in order to show a particulr hover (ok now we have just one).
About the second one...there might be a problem I can investigate...

**Comment by arichiardi** [comment]
I have also a problem [here](https://github.com/arichiardi/ccw/blob/master/ccw.core/src/clj/ccw/repl/view_helpers.clj#L77) as I think exactly what you are describing is happening...

**Comment by laurentpetit** [comment]
I switched back to working on repl / nrepl / cider, etc., will take a look at it again later

**Comment by arichiardi** [comment]
:+1:  while you are looking at it, there is a little delay given by the fact that our repl is started with a delay on the UI thread. Maybe I can improve on it using a future + promise to run it asynchronously...
Another idea I had was to add an eclipse test/variable (for whenActive, whenEnable in pom.xml) for testing if Repl is running and show/hide command/handlers accordingly...but ok...now I'd better fix my bugs ahaha

**Comment by arichiardi** [comment]
I would like that you have a look at the last commit...I thought I did a good deed, but I broke colors instead. In any case, now it's working again.

**Comment by arichiardi** [comment]
Hi Laurent, in order to pull this in, what can I do? I think there are a couple of fixes worth adding and I would like to help you in order to merge it...

**Comment by laurentpetit** [comment]
Well, my commit is far from being ready to be published yet. I'll work on it with the highest priority above all other tasks so I can share it ASAP.

I'll also look at your other PR as well of course, ASAP. Cheers.

**Comment by laurentpetit** [comment]
Whoops, I answered on the wrong PR sorey

**Comment by laurentpetit** [comment]
can I close this one for the moment?

**Comment by arichiardi** [comment]
Yes sure.

**Pull request closed without merging**
