### PR TITLE
Macro expansion hover

### PR DESCRIPTION
**Pull request by arichiardi**
Hello Laurent,
I so like this addition :smile:  I still have some problem with the size of the html hover with ```<pre>``` tags, but I am going to try some other hack to make it work...nonetheless, it correctly shows hover expansion...and I reckon it can be very useful for users.

Form the git message:

    a second hover, which performs macro expansion if a repl is available, has been added to the group.
    It expands using either the standard clojure.core/macroexpand method or cider-nrepl middleware (which has been configured with display-namespaces=tidy).
    The Macro hover has default key modifier set to Ctrl.

### CODE REVIEW

**Comment by laurentpetit** [comment]
Planned for the release, as it seems close to done

**Comment by arichiardi** [comment]
Yep, i am planning to fix the hover size within one two days...the hover looks stable, it executes every time the meta includes macro ...a question: would it make sense to include a hover for macroexpand-all?
In my opinion yes, it could be bound to a different modifier (say Ctrl-Shift) for when you need deep expansion...

**Comment by arichiardi** [comment]
This is ready on my side, to be tested on yours :smile:

**Comment by arichiardi** [comment]
Ok this should wrap up this PR with a pop :smile:

**Comment by laurentpetit** [comment]
Great feature, I just started to test it !

Working great!

Ok, now some reservations (sorry):
- did not work without cider (same input as output, e.g. I see (spy (+ 1 2)) ==> (spy (+ 1 2))
- I don't know if it's with this feature or a little bit earlier, but invoking hovers from within the REPL input area does not work

**Comment by arichiardi** [comment]
Ok..debugging...

**Comment by arichiardi** [comment]
Found, I assumed  ```macroexpand-all``` to be in ```clojure.core``` but it is in ```clojure.walk```. Patching..

**Comment by arichiardi** [comment]
will debug the second issue as well

**Comment by arichiardi** [comment]
@laurentpetit for the second bug I need some refactoring:

Basically ```ReplView``` is passed to the hover funcs (as ```text-viewer``` parameter) and therefore needs to have some notion of ```getCorrespondingREPL``` + ```getSafeConnection```.
In my old PR, the one with that huge refactoring, I had pulled out these two functions in a ```IReplAwarePart``` interface that defines parts which know about a repl (has-a relationship).

Do you think it is a good idea to reproduce it here as well?

To be honest, the Repl side is something I would like to (re)work on and extrapolate a service that maps projects to their repl session(s) (why not, more then one repl per project, one for test, one for pre-prod, one for production...maybe soon this will be even in ```core```).

Waiting for your opinion here before proceeding.

**Comment by laurentpetit** [comment]
Actually, a REPLView knows which corresponding REPL, it's itself ! Same for the safe connection, it's derived from itself! I hadn't noticed this regression sooner in the refactoring.
So yes, the REPL view is totally aware that it is a REPL, if you ask me :-)

The subject of REPL affinity for editors / projects is a tough one. The current situation, which is "always send to the corresponding REPL - which is defined as 'last active REPL' for editors, and 'this for REPLs-" is the one which makes thinks very easy to explain, very easy to understand, and very powerful (no restriction for the user).

For instance, it allows to send code from any editor to the last active repl. No need to "bind" things, to rely on workspace resolution between projects, etc.

The problem is that with the advent of ClojureScript, there IS the need for REPL affinity, at least for code seen as clojure versus clojurescript.

But having been there already, I would be very careful before trying to be "too smart" at the cost of making things hard to understand for users.

**Comment by arichiardi** [comment]
Ok I found out why, basically the part where we override ```getCorrespondingREPL``` and ```getSafeToolingConnection``` with an actual instance was in ```ClojureEditor``` only and not in ```ReplView```.
But if ```ReplView already know that he has/is a repl then it means that it will just need to always return [this](https://github.com/laurentpetit/ccw/blob/master/ccw.core/src/java/ccw/editors/clojure/ClojureEditor.java#L152) as well no?
So I could just move that implementatoin in ```ClojureSourceViewer``` and avoid overriding...am I right?
I am double checking with you as I am not sure I am interpreting the code properly..

**Comment by laurentpetit** [comment]
I see this as sharing an implementation detail of a contract. As soon as you decide to do something else for ClojureEditors, it may start to act weirdly for REPLs, no ?

**Comment by laurentpetit** [comment]
Maybe I did the wrong thing at the time. I would just let the methods abstract if there is a shared base class, and define it in both ClojureEditor and REPLView.

**Comment by laurentpetit** [comment]
Also, to answer a question you asked: for sure the REPLView needs refactoring. To be honest I was not involved in its design ;-) but really it is too coupled to everything else and I never felt comfortable with it:

- impossible to easily reuse its UI with another repl back-end (think tomorrow with either nREPL, or clojure core Socket REPLs)
- don't remember the other issues, but there are plenty

At least in the current situation, all the crap is (mostly) in the same place ;)

**Comment by arichiardi** [comment]
In any case we will need to have that piece of code in the two places. To me the contract should be ```IReplAwarePart``` which then has that implementation in both ```ClojureEditor``` and ```ReplView```...

**Comment by arichiardi** [comment]
Yes, we have said the same thing...

**Comment by laurentpetit** [comment]
I agree

2015-05-21 21:42 GMT+02:00 Andrea Richiardi <notifications@github.com>:

> In any case we will need to have that piece of code in the two places. To
> me the contract should be IReplAwarePart which then has that
> implementation in both ClojureEditor and ReplView...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/776#issuecomment-104399378>.
>



-- 
Laurent Petit

**Comment by arichiardi** [comment]
The only little problem is that the ```ClojureSourceViewer``` is sent in as parameter to the hover, and therefore I have to change bit things ...remove ```getCorrespondingREPL``` and ```getSafeToolingConnection``` from ```ClojureSourceViewer``` is possible but I will need to have a ```getEditor``` ...

**Comment by arichiardi** [comment]
About your answer up up, it is not clear to me why ```ClojureScript``` needs affinity. Maybe because I haven't "played" with it yet..

**Comment by laurentpetit** [comment]
Honestly I haven't the diagram of the new interfaces in my head.
... thinking out loud ...
the hover needs to be passed a way to connect to a REPL, fo sure, or maybe not, what it wants is a connection .... does it make sense that the connection is provided to the hover through the source viewer ... not really .... should it get an additional parameter for the connection? Even if it's implemented as the same object for the editor?

**Comment by laurentpetit** [comment]
WRT clojurescript : mixed clojure/clojurescript project is an example of a realistic minimal use case where , even for a single project, it makes sense to have 2 REPLs open at the same time, and for sure the user will expect content of .clj files to be sent to the "Last Active Clojure REPL", and content of .cljs files sent to the "Last Active ClojureScript REPL". But it's currently not clear that a REPL is a Clojure REPL or a ClojureScript REPL. I'm thinking about this on my hammock time. The current behavior allows the user to do whatever they want: they just have to click on the REPL they want to work with.
This is an area where we will probably be able, also, to learn from (success/failure) experiments of other IDEs?

**Comment by arichiardi** [comment]
You are definitely right about the ISourceViewer/ITextViewer as it does not make sense to get a repl from its contract.
However, adding a repl param to the hovers is not that easy as they are lazily created through the IExecutableExtension mechanism...but it is an interesting issue to ponder on..

**Comment by arichiardi** [comment]
Oh OK now it's clear thanks for explaining me that :)

**Comment by laurentpetit** [comment]
Thinking out loud again ... would it make sense to leverage the Eclipse Event Bus, and from the hover send a "need macro expansion" kinda event, with data describing the context of the hover, the text of the macro call to expand, and a promise. Then the hover waits for the promise to be delivered, with a timeout of course (if nobody picks the event, you don't want to block the UI forever).
This could be a way to decouple the UI (hover action and hover display) from the logic.

**Comment by arichiardi** [comment]
It is a good idea, but it would need to change a lot of things...I thought I could leverage Eclipse's separation of concerns, but indeed hover creation and display are tied at the moment...

**Comment by arichiardi** [comment]
Another thing that scares me about such a change is to recreate instances when the repl changes. It might be worth to have an ObservableValue that is holding the reference to the last repl, filled by whoever starts it, and obtainable through injection for reading.

**Comment by arichiardi** [comment]
About the Repl in input to the hover, I was thinking of implementing a [service](http://www.vogella.com/tutorials/OSGiServices/article.html) in some other PR, which I will discuss before with you in an new issue. For now, I will just put a patch on the bug by duplicating the code that we wrote above..

**Comment by arichiardi** [comment]
Need to fix here, working on it...

**Comment by laurentpetit** [comment]
too late, I merged it without testing. The fix is easy, working on it

**Pull request merged**
