### PR TITLE
Hovers step1

### PR DESCRIPTION
**Pull request by arichiardi**
Hello Laurent,

I rebased and split my "color-refactoring" feature. This is step one, where I also fixed something. I dedicated some time here because I really think that this pull requests can improve CCW (especially the next one about the interfaces, that we will discuss in a separate PR) and it is worth working on it on Sunday :D

As usual, this works iin my Kepler, but I would like you to check it out and tell me if/what I need to improve/change.

Thank you!

### CODE REVIEW

**Comment by laurentpetit** [comment]
OK. I have some Internet connectivity where I am this week, so I hope being able to make progress on this PR as well

**Comment by laurentpetit** [comment]
are you sure We shouldn't see just a fraction of the commits? Just asking (I see 6 commits)

**Comment by arichiardi** [comment]
Yes, this is just part1, then I will rebase and open a second PR for the other "trance". This adds hover support, you second and I will add it in Changelog.adoc

**Comment by laurentpetit** [comment]
Still reviewing the commits, which are quite impressive. I already have some remarks/questions to do, not necessarily big, but that's how I work, sometime thinking out loud, and focusing on tiny things to understand ... all that to say I hope you won't be too bothered by the amount or minutia in some questions.

But what's missing most to me, right now, is an overall picture of what you tried to achieve, what's visible for the user (there was already, for the user a "hover" feature for clojure vars), what's not visible for the user but of interest for CCW contributors.
Some kind of RATIONALE for the feature. This seems especially important for me because the feature will take a long time to properly review and comment. I'm discovering things along the reading, but it would be interesting to get the bottom line upfront.

**Comment by arichiardi** [comment]
Ok the rationale:
When i was developing java in Eclipse i was very fond of the feauture that allowed me to hover on some code while holding a shortcut. This was generating different hovers based on many things..context and position mostly.
I have basically taken this idea in jdt and added it to Ccw. Hover-srep1 is the first series of all i did while implementing this feature that is basically split in two:

1) Add the hover preference page so that the user can configure her shortcuts
2) Add an extension point for developers to seamlessly add new hovers without digging too much in the code

Note that a hover is potentially a rich user interface that can trigger user actions. I worked on this architectural aspect in other commits,that i would like you to check later on, step by step..part of color-refactoring. 

The big picture is to have different hovers for displaying different things. For example a hover for docstrings, one for meta data,one for the source, one for ...kibit checks..one for typed clojure lint checks...all potentially with buttons to trigger more stuff..

While i was working, it took a while, i also refactored things that i would like to discuss with you, not in this patch but in the next..this one is merely adding the base of the hover framework...

Don't worry about minutiae (nice latin word btw), it is necessary for good engineering :)

**Comment by arichiardi** [comment]
I would like to add that the feature strives to be totally pluggable, both through extensions which can be changed at runtime (try to start a new osgi plugin which extends the hover extension point) and in using databinding and observables (the HoverPreferencePage follows MVVM).

I also added tests because i knew this onewas going to be long to code review...

Sorry for typos but i am on the phone..

**Comment by laurentpetit** [comment]
I will continue code review later. I'm near the middle of the second commit. I have stopped just before reviewing the content of `CCWPlugin`. Maybe I could wait for your first reaction before continuing.
I hope you're not too afraid of the number of remarks I've done. I was inspired, and I think I owe you to carefully review the product of your work, it's a mark of respect, after all -:)

**Comment by arichiardi** [comment]
Go ahead, i am pumped up! I woke up, saw 68/69 emails from github and wanted immediately to start fixing them :)) bus OK i will nave breakfast first, thanks Laurent

**Comment by laurentpetit** [comment]
I will finish commenting the second commit. Then wait for your fixes /
remarks. Because some of my comments also denote some lacks of knowledge
from my part, so it'll be good to synchronize ourselves before I go through
the whole PR (which is already quite big, took me a while to do just what I
did yesterday night ;) )

Le mardi 28 avril 2015, Andrea Richiardi <notifications@github.com> a
écrit :

> Go ahead, i am pumped up! I woke up, saw 68/69 emails from github and
> wanted immediately to start fixing them :)) bus OK i will nave breakfast
> first, thanks Laurent
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/746#issuecomment-96948501>.
>


-- 
Laurent Petit

**Comment by arichiardi** [comment]
And again I thank you :D
To your knowledge, is there i way to see github comments inline in you cljs? I mean through emacs or ccw. It would be very helpful!

**Comment by arichiardi** [comment]
I am going to add the changes this way so that then I can fix them up with rebase in the right commit when everything is ready.

**Comment by arichiardi** [comment]
Ok done, if you give me the nod, i will rebase, fixup and push.

**Comment by laurentpetit** [comment]
:+1:

**Comment by laurentpetit** [comment]
(that was the nod)

**Comment by arichiardi** [comment]
I am still checking the new E4 things I added in order to improve them.
For example, I found a nice blog post [here](http://eclipsesource.com/blogs/tutorials/eclipse-4-e4-tutorial-soft-migration-from-3-x-to-eclipse-4-e4/).

**Comment by arichiardi** [comment]
[Another](http://eclipsesource.com/blogs/tutorials/eclipse-4-e4-tutorial-part-4-dependency-injection-basics/) one.

**Comment by laurentpetit** [comment]
Will read the links, thanks!

Le mercredi 29 avril 2015, Andrea Richiardi <notifications@github.com> a
écrit :

> Another
> <http://eclipsesource.com/blogs/tutorials/eclipse-4-e4-tutorial-part-4-dependency-injection-basics/>
> one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/746#issuecomment-97338726>.
>


-- 
Laurent Petit

**Comment by arichiardi** [comment]
I have simplified a bit, after having asked on the Eclipse forum, but basically we are still a little bit tied with 3.x (e4 does not have activators/AbstractUIPlugin). So I think I can leave it like this now. Moreover I have removed ```_content-type``` from ```select-hover-by-state-mask```, thinking that we will add it as needed.

**Comment by arichiardi** [comment]
Again, when you give me the nod, I will rebase...sorry I wanted to check the injection part and I have worked a bit more on this PR.

**Comment by laurentpetit** [comment]
No problem, there's no rush and you can work on it as you see fit.

I'd like to take the time, albeit later today, to check the
simplifications. If you want to go ahead, you can maybe rebate locally,
create a new branch and a new PR, and leave the current branch/PR as is?

Le mercredi 29 avril 2015, Andrea Richiardi <notifications@github.com> a
écrit :

> Again, when you give me the nod, I will rebase...sorry I wanted to check
> the injection part and I have worked a bit more on this PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/laurentpetit/ccw/pull/746#issuecomment-97379206>.
>


-- 
Laurent Petit

**Comment by arichiardi** [comment]
Agree

**Comment by laurentpetit** [comment]
Can I close this particular  PR since it's superseded by the other one?

**Comment by arichiardi** [comment]
Yes

**Pull request closed without merging**
